# Generated by Django 3.2.7 on 2021-10-15 04:23

import apps.uploads.models.upload
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.uploads.models.upload.upload_to)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
